"""Embedded panel wake/init frames — GENERATED by dev/src-re/make_wake.py, do not edit.

The wake-lite sequence: 32 VERBATIM isoc URBs from baseline-app-starting.pcapng
(dev/pcap), cut at the capture's first op35/op36 element draw. They bring the panel's render
pipeline up (session blob, screen config, brightness) without painting the vendor app's own
icons/labels. Embedded so the runtime needs no data files (observe-and-copy: these are the
real captured bytes, only re-serialized).
"""
import base64
import zlib

_LENS = [1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904, 1904]

_B64 = (
    "eNrt3b1rU1EYwOFzk9ba2mpaWz9brXbqZC1BOoj0ooEIdtDSXaE6+A84uCRtRMTdQScHB0E3B3Gxf4A46KLix+qgg6DgIrU5"
    "9EJU3Dxo5Xkol3PfQ5Y3ww+6pF47c3zhVG0+ABvG/NzB8HghC5Wsb+3t8/kj46ezzvtBK4J/Tl1vYQP29mN4e7sUhofab1Nr"
    "f1mYKoWpcpj+7WdmfnqvFofZ+MxDWAkr1UYxjIe8EYdFy2fjIc/isFkM4yFvxmGpGMZDXorDpWIYD/lSHJaLYTzk5ThcLobx"
    "kC+3h75t9Bb4e73tC91D5TBsFaC3QNLePrvWpbegt0Di3k486tZb0FsgaW97Q+X5JosAvQUS9/bNRI9FgN4CiXv76dJmiwC9"
    "BRL39ujVXosAvQUS9/bsjT6LAL0FEvf2/oUtFgF6CyTu7YsH/RYBegsk7u3IiQGLAL0FEvf25MJWiwC9BRL3tnVnm0WA3gKJ"
    "ezv4rWIRoLdA4t6+HvArt6C3QOreNkaHLAL0Fkjc27kP2y0C9BZI3NuZY36ND/QWSN3bL09HLAL0Fkjc27vvdlgE6C2QuLeL"
    "h3ZaBOgtkLi39cu7LAL0Fkjc2yvXd1sE6C2QuLcvb+6xCNBbIHFvhy/utQjQWyBxb889HLUI0FsgcW/v1ccsAvQWSNrbW6HR"
    "3BemQyvr6QmLvz5nQlhdV24/qqHrQPi6ulqqTdYmq431l0qr0qpmnTfNzptS581S502582a548Z3A3oL/1Nvx0L/k/3hcPZD"
    "WbvaD9sBvQX+3P+TX70ftwjYQL4DL3Dhmg=="
)


def frames():
    """-> list of 32 wake URBs (bytes), verbatim."""
    raw = zlib.decompress(base64.b64decode("".join(_B64)))
    out, off = [], 0
    for n in _LENS:
        out.append(raw[off:off + n])
        off += n
    assert off == len(raw)
    return out
